version: "3"
networks:
  expense:
volumes:
  mysql:    # equivalent to 'docker volume create mysql'
services:
  mysql:
    image: yswnth/mysql:v1
    container_name: mysql   # --name mysql
    volumes:
    - mysql:/var/lib/mysql  # -v mysql:/var/lib/mysql
  backend:
    image: yswnth/backend:v1
    container_name: backend
    command: sh -c "sleep 20 && node /opt/server/index.js" # to delay the start of application unitil mysql starts completely
    depends_on:
    - mysql
  frontend:
    image: yswnth/frontend:v1
    container_name: frontend
    ports:
    - 80:80   # -p 80:80
    depends_on:
    - backend